-- Script: MCT_CreateTables.sql.
-- Description: MCT_CreateTables.sql v2.00 follow by quyqv design v0.5.
-- DB server: Microsoft SQl server.
-- Created date: 03/12/2021.
-- Last updated: 10/12/2021.
-- Author: trongtd@meta-vi.vn.

-- Create the database.

USE MASTER
GO

IF NOT EXISTS (
   SELECT NAME
   FROM sys.databases
   WHERE NAME = N'MCTProject'
)
CREATE DATABASE [MCTProject]
GO

USE [MCTProject]
GO

---
--- Drop tables
---

DROP TABLE IF EXISTS dbo.CHAT_PARTICIPANT;
DROP TABLE IF EXISTS dbo.CHAT_MESSAGE;
DROP TABLE IF EXISTS dbo.CALL_PARTICIPANT;
DROP TABLE IF EXISTS dbo.CHAT_ROOM;
DROP TABLE IF EXISTS dbo.CALL_GROUP;
DROP TABLE IF EXISTS dbo.CONTACT;
DROP TABLE IF EXISTS dbo.ACCOUNT;

---
--- Create tables
---

---
--- 1. Name: ACCOUNT; Type: TABLE; Schema: dbo; Owner: -; Tablespace:
---
CREATE TABLE dbo.ACCOUNT(
	ACCOUNT_ID INT NOT NULL,
	USER_NAME VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(30) NOT NULL,
	LAST_TIME_LOG_IN DATETIME NOT NULL,
	STATUS SMALLINT NOT NULL,
	FIRT_NAME NVARCHAR(30) NOT NULL,
	LAST_NAME NVARCHAR(30) NOT NULL,
	GENDER SMALLINT NOT NULL,
	ROLE SMALLINT NOT NULL,

	PRIMARY KEY (ACCOUNT_ID)
)

---
--- 2. Name: CONTACT; Type: TABLE; Schema: dbo; Owner: -; Tablespace:
---
CREATE TABLE dbo.CONTACT(
	CONTACT_ID INT NOT NULL,
	ACCOUNT_ID INT NOT NULL,
	STARTDATE DATETIME NOT NULL,
	BLOCKED SMALLINT NOT NULL,

	PRIMARY KEY (CONTACT_ID),
	FOREIGN KEY (ACCOUNT_ID) REFERENCES dbo.ACCOUNT
)

---
--- 3. Name: GROUP; Type: TABLE; Schema: dbo; Owner: -; Tablespace:
---
CREATE TABLE dbo.[GROUP](
	GROUP_ID INT NOT NULL,
	GROUP_NAME NVARCHAR(60) NOT NULL,
	CREATED_TIME DATETIME NOT NULL,
	CREATED_BY_ACCOUNT_ID INT NOT NULL,
	STATUS SMALLINT NOT NULL,

	PRIMARY KEY (GROUP_ID)
)

---
--- 4. Name: CALL_PARTICIPANT; Type: TABLE; Schema: dbo; Owner: -; Tablespace:
---
CREATE TABLE dbo.CALL_PARTICIPANT(
	CALL_ID INT NOT NULL,
	ACCOUNT_ID INT NOT NULL,
	GROUP_ID INT NOT NULL,
	START_TIME DATETIME NOT NULL,
	END_TIME DATETIME NOT NULL,

	PRIMARY KEY (CALL_ID),
	FOREIGN KEY (ACCOUNT_ID) REFERENCES dbo.ACCOUNT,
	FOREIGN KEY (GROUP_ID) REFERENCES dbo.[GROUP]
)

---
--- 5. Name: GROUP_PARTICIPANT; Type: TABLE; Schema: dbo; Owner: -; Tablespace:
---
CREATE TABLE dbo.GROUP_PARTICIPANT(
	ACCOUNT_ID INT NOT NULL,
	GROUP_ID INT NOT NULL,
	LAST_SEEN_MESSAGE_ID BIGINT NOT NULL,

	PRIMARY KEY (ACCOUNT_ID, GROUP_ID),
	FOREIGN KEY (ACCOUNT_ID) REFERENCES dbo.ACCOUNT,
	FOREIGN KEY (GROUP_ID) REFERENCES dbo.[GROUP]
)

---
--- 6. Name: CHAT_MESSAGE; Type: TABLE; Schema: dbo; Owner: -; Tablespace:
---
CREATE TABLE dbo.CHAT_MESSAGE(
	MESSAGE_ID BIGINT NOT NULL,
	ACCOUNT_ID INT NOT NULL,
	GROUP_ID INT NOT NULL,
	MESSAGE_CONTEXT NVARCHAR(256) NOT NULL,
	SENT_TIME DATETIME NOT NULL,
	STATUS SMALLINT NOT NULL,

	PRIMARY KEY (MESSAGE_ID),
	FOREIGN KEY (ACCOUNT_ID) REFERENCES dbo.ACCOUNT,
	FOREIGN KEY (GROUP_ID) REFERENCES dbo.[GROUP]
)
