-- Create the database
USE MASTER
GO

IF NOT EXISTS (
   SELECT NAME
   FROM sys.databases
   WHERE NAME = N'MCTProject'
)
CREATE DATABASE [MCTProject]
GO

USE [MCTProject]
GO

-- Create tables
CREATE TABLE dbo.ACCOUNT(
	ACCOUNT_ID INT NOT NULL,
	USER_NAME VARCHAR(30) NOT NULL,
	PASS_WORD VARCHAR(30) NOT NULL,
	LAST_TIME_LOG_IN DATETIME NOT NULL,
	BLOCKED SMALLINT NOT NULL,
	EXPIRED SMALLINT NOT NULL,
	FIRST_NAME NVARCHAR(30) NOT NULL,
	LAST_NAME NVARCHAR(30) NOT NULL,
	GENDER SMALLINT NOT NULL,
	ROLE SMALLINT NOT NULL,
	PRIMARY KEY (ACCOUNT_ID)
)
GO

CREATE TABLE dbo.CHAT_ROOM(
	ROOM_ID INT NOT NULL,
	ROOM_NAME NVARCHAR(60) NOT NULL,
	CREATED_TIME DATETIME NOT NULL,
	CREATED_BY_ACCOUNT_ID INT NOT NULL,
	STATUS SMALLINT NOT NULL,
	PRIMARY KEY (ROOM_ID)
)
GO

CREATE TABLE dbo.CHAT_MESSAGE(
	MESSAGE_ID INT NOT NULL,
	ACCOUNT_ID INT FOREIGN KEY REFERENCES ACCOUNT(ACCOUNT_ID) NOT NULL,
	ROOM_ID INT FOREIGN KEY REFERENCES CHAT_ROOM(ROOM_ID) NOT NULL,
	MESSAGE_CONTEXT NVARCHAR(256) NOT NULL,
	SENT_TIME DATETIME NOT NULL,
	STATUS SMALLINT NOT NULL,
	PRIMARY KEY ( MESSAGE_ID, ACCOUNT_ID, ROOM_ID),
	
)
GO

CREATE TABLE dbo.CHAT_PARTICIPANT(
	ROOM_ID INT FOREIGN KEY REFERENCES CHAT_ROOM(ROOM_ID) NOT NULL,
	ACCOUNT_ID INT FOREIGN KEY REFERENCES ACCOUNT(ACCOUNT_ID) NOT NULL,
	LAST_SEEN_MESSAGE_ID INT
)
GO

CREATE TABLE dbo.CALL_GROUP(
	GROUP_ID INT NOT NULL,
	GROUP_NAME NVARCHAR(60) NOT NULL,
	CREATED_TIME DATETIME NOT NULL,
	CREATED_BY_ACCOUNT_ID INT NOT NULL,
	STATUS SMALLINT NOT NULL,
	PRIMARY KEY (GROUP_ID)
)
GO

CREATE TABLE dbo.CALL_PARTICIPANT(
	CALL_PARTICIPANT_ID INT NOT NULL,
	GROUP_ID INT  FOREIGN KEY REFERENCES CALL_GROUP(GROUP_ID) NOT NULL,
	ACCOUNT_ID INT FOREIGN KEY REFERENCES ACCOUNT(ACCOUNT_ID) NOT NULL,
	START_TIME DATETIME NOT NULL,
	END_TIME DATETIME NOT NULL,
	CALL_TIME INT NOT NULL,
	PRIMARY KEY (CALL_PARTICIPANT_ID)
)
GO
